x-veld:
  code:
    description: "word2vec training setup"
    topics:
      - "NLP"
      - "Machine Learning"
      - "word embeddings"

    inputs:
      - volume: /veld/input/
        environment: in_train_data_file
        description: "training data. Must be one single txt file, one sentence per line."
        file_type: "txt"
        contents:
          - "NLP training data"
          - "word embeddings training data"
          - "raw text"

    outputs:
      - volume: /veld/output/
        environment: out_model_file
        description: "self trained word embeddings word2vec model"
        file_type: "word2vec model"
        contents:
          - "NLP model"
          - "word embeddings model"

    settings:
      - environment: train_data_description
        description: "short human description for the kind of training data"
        env_type: "str"
        optional: true
      - environment: model_description
        description: "short human description for the overall model and its purpose"
        env_type: "str"
        optional: true
      - environment: epochs
        description: "word2vec hyperparameter: number of training epochs"
        env_type: "int"
        optional: true
        default: 50
      - environment: vector_size
        description: "word2vec hyperparameter: number of dimensions of the word vectors"
        env_type: "int"
        default: 200
      - environment: window
        description: "word2vec hyperparameter: number of surrounding context words to be used for training."
        env_type: "int"
        default: 3
      - environment: min_count
        description: "word2vec hyperparameter: minimal number of occurrence for each word to be used for training."
        env_type: "int"
        default: 5
          
services:
  veld_train:
    build: .
    command: python /veld/code/train.py
    volumes:
      - ./src/train/:/veld/code/:z
      - ./data/training_data/:/veld/input/:z
      - ./data/models/:/veld/output/:z
    environment:
      in_train_data_file: null
      out_model_file: null
      model_description: null
      epochs: 50
      vector_size: 200
      window: 3
      min_count: 5

