x-veld:
  code:
    description: "a word2vec jupyter notebook, for quick experiments"
    topic:
      - "NLP"
      - "Machine Learning"
      - "word embeddings"

    input:
      - volume: /veld/input/
        description: "arbitrary storage for word2vec experiments"
        file_type:
          - "word2vec model"
          - "training data"
          - "NLP training data"
          - "raw text"
        content:
          - "NLP model"
          - "word embeddings model"
          - "model metadata"
          - "NLP training data"
          - "word embeddings training data"
          - "raw text"
    output:
      - volume: /veld/output/
        description: "arbitrary storage for word2vec experiments"

services:
  veld_jupyter_notebook:
    build: .
    command: jupyter notebook --allow-root --ip='*' --NotebookApp.token='' --NotebookApp.password=''
    ports:
      - 8888:8888
    volumes:
      - ./src/jupyter_notebook/:/veld/code/:z
      - ./data/input/:/veld/input/:z
      - ./data/output/:/veld/output/:z

