x-veld:
  executable:

    inputs:
      volume: /veld/input/
      type:
        - "csv"
        - "txt"
      content: 
        - "NLP training data"
        - "NLP data"

    outputs:
      volume: /veld/output/
      type: "word2vec model"
      content:
        - "NLP model"
        - "word embeddings model"

    environment:
      train_data_path:
        description: "path to training data file"
        type: string
        path_prefix: "/veld/input/"
      train_data_description:
        description: "short human description for the kind of training data"
        type: string
        optional: true
      model_path:
        description: "path to model file"
        type: string
        path_prefix: "/veld/output/"
      training_architecture:
        description: "short label for the overall training setup"
        type: string
      model_id: 
        description: "id for the specific model"
        type: string
      vector_size: 
        description: "word2vec hyperparameter"
        type: int
      window: 
        description: "word2vec hyperparameter"
        type: int
      min_count: 
        description: "word2vec hyperparameter"
        type: int
          
services:
  veld:
    build: .
    ports:
      - 8888:8888
    volumes:
      - ./src/train/:/veld/executable/
    working_dir: /veld/executable/
    command: jupyter notebook --ip='*' --NotebookApp.token='' --NotebookApp.password='' --allow-root

