x-veld:
  executable:

    inputs:
      volume: /veld/input/
      type:
        - "csv"
        - "txt"
      content: 
        - "NLP training data"
        - "NLP data"

    outputs:
      volume: /veld/output/
      type: "word2vec model"
      content:
        - "NLP model"
        - "word embeddings model"

    environment:
      train_data_path:
        path_prefix: "/veld/input/"
        description: "path to training data file"
        type:
          - "csv"
          - "txt"
      train_data_description:
        description: "short human description for the kind of training data"
        type: string
        optional: true
      model_path:
        path_prefix: "/veld/output/"
        description: "path to model file"
        type: "word2vec model"
      training_architecture:
        description: "short label for the overall training setup"
        type: string
      model_id: 
        description: "id for the specific model"
        type: string
      vector_size: 
        description: "word2vec hyperparameter"
        type: int
      window: 
        description: "word2vec hyperparameter"
        type: int
      min_count: 
        description: "word2vec hyperparameter"
        type: int
          
services:
  veld:
    build: .
    ports:
      - 8888:8888
    volumes:
      - ./volumes/train/input/:/veld/input/
      - ./volumes/train/output/:/veld/output/
      - ./src/train/:/veld/executable/
    working_dir: /veld/executable/
    command: jupyter notebook --ip='*' --NotebookApp.token='' --NotebookApp.password='' --allow-root
    environment:
      train_data_path: "/veld/input/<REPLACE>"
      train_data_description: "<REPLACE>"
      model_path: "/veld/output/<REPLACE>"
      training_architecture: "<REPLACE>"
      model_id: "<REPLACE>"
      vector_size: 500
      window: 5
      min_count: 5

