x-veld:
  executable:

    inputs:
      description: "uncleaned or unprocessed training data"
      volume: /veld/input/
      type: "csv"
      content: 
        - "NLP training data"
        - "NLP data"

    outputs:
      description: "cleaned or processed training data"
      volume: /veld/output/
      type:
        - "csv"
        - "txt"
      content: 
        - "NLP training data"
        - "NLP data"

    environment:
      unprocessed_file_name:
        description: "path to unprocessed data file"
        type: string
        prefix: "/veld/input/"
      processed_file_name:
        description: "path to processed data file"
        type: string
        prefix: "/veld/output/"

  chain_template: # you can copy this template below into a new chain veld.yaml for using this executable
    x-veld:
      chain:
    services:
      veld:
        extends:
          file: ./<REPLACE_WITH_ROOT_FOLDER_OF_EXECUTABLE>/veld_preprocess.yaml
          service: veld
        volumes:
          - ./<REPLACE_WITH_ROOT_FOLDER_OF_UNPROCESSED_DATA>/:/veld/input/
          - ./<REPLACE_WITH_ROOT_FOLDER_OF_PROCESSED_DATA>/:/veld/output/
        environment:
          unprocessed_file_path: "/veld/input/<REPLACE>"
          processed_file_path: "/veld/output/<REPLACE>"
          
services:
  veld:
    build: .
    ports:
      - 8888:8888
    volumes:
      - ./src/clean/:/veld/executable/
    working_dir: /veld/executable/
    command: jupyter notebook --ip='*' --NotebookApp.token='' --NotebookApp.password='' --allow-root

